version: "3.7"

services:

  flask:
    #image: vetter1223/docker-simple_flask
    build: ./flask
    container_name: flask
    restart: always
    expose:
        - "9000"
    command: gunicorn -w 3 -b 0.0.0.0:9000 run:app

  nginx:
    #image: vetter1223/docker-simple_nginx
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
        - "5000:5000"
    depends_on:
        - flask